export const INCREMENT_SPICE_LEVEL = "INCREMENT_SPICE_LEVEL"
export type INCREMENT_SPICE_LEVEL = typeof INCREMENT_SPICE_LEVEL

export const DECREMENT_SPICE_LEVEL = "DECREMENT_SPICE_LEVEL"
export type DECREMENT_SPICE_LEVEL = typeof DECREMENT_SPICE_LEVEL

export const RETRIEVE_POSTS = "RETRIEVE_POSTS"
export type RETRIEVE_POSTS = typeof RETRIEVE_POSTS
