export const INCREMENT_SPICE_LEVEL = "INCREMENT_SPICE_LEVEL"
export type INCREMENT_SPICE_LEVEL = typeof INCREMENT_SPICE_LEVEL

export const DECREMENT_SPICE_LEVEL = "DECREMENT_SPICE_LEVEL"
export type DECREMENT_SPICE_LEVEL = typeof DECREMENT_SPICE_LEVEL

export const RECEIVE_POSTS = "RECEIVE_POSTS"
export type RECEIVE_POSTS = typeof RECEIVE_POSTS

export const REQUEST_POSTS_FAILED = "REQUEST_POSTS_FAILED"
export type REQUEST_POSTS_FAILED = typeof REQUEST_POSTS_FAILED

export const REQUEST_POSTS = "REQUEST_POSTS"
export type REQUEST_POSTS = typeof REQUEST_POSTS
